name: Deploy API and UI to Azure Web Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-api:
    name: Deploy API to Azure Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install API dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r api/requirements.txt

      # - name: Run API tests (if any)
      #   run: |
      #     echo "No API tests implemented" # Replace with pytest if you have tests

      - name: Zip API app for deployment
        run: |
          cd api
          zip -r ../api.zip .

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_API_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: ./api.zip

  deploy-ui:
    name: Deploy UI to Azure Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install UI dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r ui/requirements.txt

      # - name: Run UI tests (if any)
      #   run: |
      #     echo "No UI tests implemented" # Replace with pytest if you have tests

      - name: Zip UI app for deployment
        run: |
          cd ui
          zip -r ../ui.zip .

      - name: Deploy UI to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_UI_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_UI_PUBLISH_PROFILE }}
          package: ./ui.zip